base1 = float(input('Qual o valor da primeira Base = '))
base2 = float(input('Qual o valor da segunda base = '))
exponent = float(input('Qual o valor do expoente = '))
result1 = float(base1) ** float(exponent)
result2 = float(base2) ** float(exponent)
result3 = float(result1) * float(result2)
print('(',base1,'*',base2,')','**',exponent)
print(result1,'*',result2,'=',result3)
print('Resposta=',result3)