base = float(input('Digite a base = '))
exponent1 = float(input('Digite o primeiro expoente = '))
exponent2 = float(input('Digite o segundo exponent = '))
result1 = float(exponent1) * float(exponent2)
result2 = float(base) ** float(result1)
print('(',base,'**',exponent1,')','**',exponent2)
print(base,'**',exponent1,'*',exponent2)
print(base,'**',result1)
print('Resultado=',result2)